version: '3.3'

services:
  sqs:
    image: softwaremill/elasticmq-native@sha256:fd7e2193b2cdc6d69b20b353ba385fef8f68955ddd1bd64e32648f650f566503
    volumes:
      - type: bind
        source: ./local/mq/elasticmq/elasticmq.conf
        target: /opt/elasticmq.conf
    ports:
      - "9324:9324"
      - "9325:9325"
  arangodb:
    image: arangodb-service
    environment:
      - ARANGO_NO_AUTH=true
    volumes:
      - type: volume
        source: arangodb
        target: /var/lib/arangodb3
      - type: bind
        source: ./local/db/arangodb/entrypoint.sh
        target: /entrypoint.sh
      - type: bind
        source: ./local/db/arangodb/initdb.d
        target: /initdb.d
    ports:
      - "8529:8529"

volumes:
  arangodb:
